src/Entity/Calender.php
<?php

namespace App\Entity;

use App\Repository\CalenderRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CalenderRepository::class)
 */
class Calender
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

     /**
     * @ORM\Column(type="string", length=100)
     */
    private $title;
    
    /**
     * @ORM\OneToOne(targetEntity=Courses::class, cascade={"persist", "remove"})
     */
    private $course;

       /**
     * @ORM\Column(type="datetime")
     */
    private $start;

    /**
     * @ORM\Column(type="datetime")
     */
    private $end;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $background_color;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $border_color;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $text_color;

    public function getId(): ?int
    {
        return $this->id;
    }
    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(\DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }


    public function getBackgroundColor(): ?string
    {
        return $this->background_color;
    }

    public function setBackgroundColor(string $background_color): self
    {
        $this->background_color = $background_color;

        return $this;
    }

    public function getBorderColor(): ?string
    {
        return $this->border_color;
    }

    public function setBorderColor(string $border_color): self
    {
        $this->border_color = $border_color;

        return $this;
    }

    public function getTextColor(): ?string
    {
        return $this->text_color;
    }

    public function setTextColor(string $text_color): self
    {
        $this->text_color = $text_color;

        return $this;
    }

    public function getCourse(): ?Courses
    {
        return $this->course;
    }

    public function setCourse(?Courses $course): self
    {
        $this->course = $course;

        return $this;
    }
}

src/Form/CalenderType.php
<?php

namespace App\Form;

use App\Entity\Calender;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ColorType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
    use App\Entity\Courses;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class CalenderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('start', DateTimeType::class, [
                'date_widget' => 'single_text'
            ])
            ->add('end', DateTimeType::class, [
                'date_widget' => 'single_text'
            ])
            ->add('background_color', ColorType::class)
            ->add('border_color', ColorType::class)
            ->add('text_color', ColorType::class)
            ->add('course' ,EntityType::class,[
                'class'=>Courses::class,
                'choice_label'=>'nom' ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Calender::class,
        ]);
    }
}

src/Controller/CalenderController.php
<?php

namespace App\Controller;

use App\Entity\Calender;
use App\Form\CalenderType;
use App\Repository\CalenderRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/calender")
 */
class CalenderController extends AbstractController
{
    /**
     * @Route("/", name="app_calender_index", methods={"GET"})
     */
    public function index(CalenderRepository $calenderRepository): Response
    {
        return $this->render('calender/index.html.twig', [
            'calenders' => $calenderRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_calender_new", methods={"GET", "POST"})
     */
    public function new(Request $request, CalenderRepository $calenderRepository): Response
    {
        $calender = new Calender();
        $form = $this->createForm(CalenderType::class, $calender);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $calenderRepository->add($calender);
            return $this->redirectToRoute('app_courses_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('calender/new.html.twig', [
            'calender' => $calender,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_calender_show", methods={"GET"})
     */
    public function show(Calender $calender): Response
    {
        return $this->render('calender/show.html.twig', [
            'calender' => $calender,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_calender_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Calender $calender, CalenderRepository $calenderRepository): Response
    {
        $form = $this->createForm(CalenderType::class, $calender);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $calenderRepository->add($calender);
            return $this->redirectToRoute('app_calender_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('calender/edit.html.twig', [
            'calender' => $calender,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_calender_delete", methods={"POST"})
     */
    public function delete(Request $request, Calender $calender, CalenderRepository $calenderRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$calender->getId(), $request->request->get('_token'))) {
            $calenderRepository->remove($calender);
        }

        return $this->redirectToRoute('app_calender_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/calender/_delete_form.html.twig
<form method="post" action="{{ path('app_calender_delete', {'id': calender.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ calender.id) }}">
    <button class="btn">Delete</button>
</form>

templates/calender/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/calender/edit.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Edit Calender{% endblock %}

{% block body %}

    <h1>Edit Calender</h1>

    {{ include('calender/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_calender_index') }}">back to list</a>

    {{ include('calender/_delete_form.html.twig') }}
{% endblock %}

templates/calender/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Calender index{% endblock %}

{% block body %}
    <h1>Calender index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Start</th>
                <th>End</th>
                <th>Background_color</th>
                <th>Border_color</th>
                <th>Text_color</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for calender in calenders %}
            <tr>
                <td>{{ calender.id }}</td>
                <td>{{ calender.start ? calender.start|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ calender.end ? calender.end|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ calender.backgroundColor }}</td>
                <td>{{ calender.borderColor }}</td>
                <td>{{ calender.textColor }}</td>
                <td>
                    <a href="{{ path('app_calender_show', {'id': calender.id}) }}">show</a>
                    <a href="{{ path('app_calender_edit', {'id': calender.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_calender_new') }}">Create new</a>
{% endblock %}

templates/calender/new.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}New Calender{% endblock %}

{% block body %}
    <div class="page-body">

    {{ include('calender/_form.html.twig') }}

    </div>
{% endblock %}

templates/calender/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Calender{% endblock %}

{% block body %}
    <h1>Calender</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ calender.id }}</td>
            </tr>
            <tr>
                <th>Start</th>
                <td>{{ calender.start ? calender.start|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>End</th>
                <td>{{ calender.end ? calender.end|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Background_color</th>
                <td>{{ calender.backgroundColor }}</td>
            </tr>
            <tr>
                <th>Border_color</th>
                <td>{{ calender.borderColor }}</td>
            </tr>
            <tr>
                <th>Text_color</th>
                <td>{{ calender.textColor }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_calender_index') }}">back to list</a>

    <a href="{{ path('app_calender_edit', {'id': calender.id}) }}">edit</a>

    {{ include('calender/_delete_form.html.twig') }}
{% endblock %}